"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
function mainHtmlBodyTemplate(url, fileName, fileSize, id) {
    var htmlBody = "<section id=\"drop-area\">\n                        <form method=\"post\" enctype=\"multipart/form-data\" name=\"formUpFiles\">\n                            <div class=\"container\" id=\"form-container\">\n                                <div class=\"row\">\n                                    <div class=\"col-xs-12\">\n                                        <div class=\"panel panel-default\">\n                                            <div class=\"panel-body\">\n                                                <span class=\"glyphicon glyphicon-cloud-upload\"></span>\n                                                <h2>File Uploader</h2>\n                                                <div class=\"progress\">\n                                                    <div class=\"progress-bar\" role=\"progressbar\"></div>\n                                                </div>\n                                                <!-- <button class=\"btn btn-lg choose-btn\" type=\"button\">Choose File</button> -->\n                                                <input id=\"choose-input\" type=\"file\" name=\"uploads[]\" multiple=\"multiple\">\n                                                <label for=\"choose-input\" class=\"btn btn-lg choose-btn\" type=\"button\">Choose File</label>\n                                                <!-- <button class=\"btn btn-lg upload-btn\" type=\"button\">Upload File</button> -->\n                                                <input type=\"submit\" class=\"btn btn-lg upload-btn\" value=\"Upload Files\" name=\"submit\">\n                                            </div>\n                                        </div>\n                                    </div>\n                                </div>\n                            </div>\n                        </form>\n                        <div id=\"selectedFiles\"></div>\n                    </section>;";

    return htmlBody;
}
exports.default = mainHtmlBodyTemplate;